### ISSUE TITLE
预览时报错,main package source size2483 KB, exceeded max limit 2MB

### ISSUE THREAD

**Issue by StarksJohn** [kala888/nice-router-taro#10]
![image](https://user-images.githubusercontent.com/7087874/102982622-ced41e80-4545-11eb-8482-31bdf004d0f2.png)

**Comment by StarksJohn** [comment]
求大佬解决下

**Comment by kala888** [comment]
@cham1985 这。。。这种问题，及时去问taro啊。。。。。一般我预览都是直接build
可以用下面命令，

 NODE_ENV=production taro build --type weapp --watch

**Comment by StarksJohn** [comment]
谢谢大佬
