### ISSUE TITLE
增加icon无效

### ISSUE THREAD

**Issue by Go-Faram** [kala888/nice-router-taro#14]
![image](https://user-images.githubusercontent.com/3043382/112403094-bba13c80-8d48-11eb-9dbb-d4c9185cb216.png)

后端返回数据，前端通过GenericPageBase渲染, taro_ui里面的icon未生效
![image](https://user-images.githubusercontent.com/3043382/112403211-f73c0680-8d48-11eb-89a4-724fb191638c.png)

**Comment by Go-Faram** [comment]
就是一个蓝色的悬浮按钮， 但是用示例里面的app icon又是可以的

**Comment by kala888** [comment]
@Go-Faram 默认的icon里面没有shopping-cart，你可以自行从iconfont 上添加font，移植到bizfont.scss
这一名字会默认添加bizfont-xxxxx
![image](https://user-images.githubusercontent.com/1215976/112406222-b941e100-8d4e-11eb-80af-2e71dde4a928.png)

**Comment by kala888** [comment]
例如icon='bizfont-docs'

**Comment by Go-Faram** [comment]
> 例如icon='bizfont-docs'

额 懂了， 还有一个currentRouter = getCurrentInstance().router 在页面一开始能获取到路由参数， 但是调用微信支付以后再回到页面， 之前获取到的参数都成undefined了 不知道怎么回事，我用调试看 页面只是自己调用l onhide onshow了几次而已, 我看官方文档, 写的是不要每次去调用，但是我就是一开始保存在变量里面的
![image](https://user-images.githubusercontent.com/3043382/112408571-ff00a880-8d52-11eb-893b-3efe68576d4a.png)

![image](https://user-images.githubusercontent.com/3043382/112408591-0c1d9780-8d53-11eb-811f-fc6b8de1e4fc.png)

**Comment by kala888** [comment]
@Go-Faram 还真没遇到过，尝试试试import { Current } from '@tarojs/taro'; 或者去问问taro的开发
