### ISSUE TITLE
EleImagePicker 组件 h5 上传无效

### ISSUE THREAD

**Issue by Go-Faram** [kala888/nice-router-taro#17]
![image](https://user-images.githubusercontent.com/3043382/112710372-87ba4880-8efb-11eb-8afc-c50777a34440.png)

选择图片后，没有根据配置地址去获取oss token, 也没有上传图片

**Comment by kala888** [comment]
Taro UI （严重怀疑属于KPI项目）的image-picker 封装的不好，后面整个上传组件和上传逻辑都会换掉。
1.Image Picker参照Taro UI自己写。
2. 前端组件只上传文件到对应的后台，不再直接上传到OSS等cdn上，原因是，现在服务前上传带宽都很大，直接上传到后台，又后台再分发到CDN。降低组件的复杂度和灵活性。
