### ISSUE TITLE
希望在listof 页面 增加一种filter, 用于应对过滤状态太多的情况

### ISSUE THREAD

**Issue by jarryscript** [kala888/nice-router-taro#26]
目前的listof页面的filter效果如下
 
![image](https://user-images.githubusercontent.com/29606832/119762162-c3639580-bedf-11eb-9024-a4d84a1585a4.png)

当过滤状态过多的，要一直往右滑，很麻烦

例如我做的企业交易流水页面如下
![image](https://user-images.githubusercontent.com/29606832/119762377-28b78680-bee0-11eb-86b1-a1250aaf61c3.png)
想根据项目或者交易对方来过滤，由于项目或交易方是持续增加的，当多到一定程度的时候，就不好用了
因此想要类似微信的这种filter
![image](https://user-images.githubusercontent.com/29606832/119762338-13425c80-bee0-11eb-9c15-47e9e56ce502.png)

**Comment by kala888** [comment]
不错的组件想法，可以考虑贡献代码哦
