### ISSUE TITLE
老哥,nice脚手架,我准备把dva去掉,切成useContext useReducer

### ISSUE THREAD

**Issue by windyzoe** [kala888/nice-router-taro#27]
感觉sorrycc也不会维护dva了,早上原生早幸福啊

**Comment by kala888** [comment]
不复杂，我尝试了，只是还没正式弄，folk一份代码，你先搞起。。。到时候我抄作业。。

**Comment by windyzoe** [comment]
还没出手,还在看你的源码,看的差不多了再出手...

**Comment by kala888** [comment]
改了
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1215976/182092083-3fc5c2b6-7694-4a4d-a306-3749364baf68.png">

尽情期待2.0
