### ISSUE TITLE
不支持支付宝吗

### ISSUE THREAD

**Issue by a869057476** [kala888/nice-router-taro#31]
支付宝中直接显示    系统错误，正在排查

**Comment by a869057476** [comment]
![image](https://user-images.githubusercontent.com/20514461/180125704-d9c72769-cd9e-4fa5-bc13-c8e8a562c69b.png)

**Comment by kala888** [comment]
内核是taro，理论上是支持支付宝的，没有调试过。不过由于现在版本是TaroUI，所有有些组件会有问题。
