### ISSUE TITLE
Cannot read property 'tap' taro

### ISSUE THREAD

**Issue by 809185396** [kala888/nice-router-taro#32]
参照开发手册上来运行，微信小程序开发工具提示Cannot read property 'tap' taro，有底部的导航，页面没有内容。h5页面底部没有导航栏和页面内容。

**Comment by kala888** [comment]
taro 版本问题，可以切换到1.0这个branch，把taro升级到3.5.4就可以了。
PS：旧的nice-router-taro，已经归档到1.0 branch, 现在的master 移除了taro-ui，移除了dva。
