### ISSUE TITLE
restart app codepush will rollback

### ISSUE THREAD

**Issue by baixjian** [kala888/nice-router-taro#37]
[update-checker](https://github1s.com/kala888/nice-router-taro/blob/b2ddd5d7f0f77c1bb5ae13f88fa265f7fd3a3615/datav-app/src/service/codepush/update-checker.tsx#L13-L14)
在APP 首次安装， 执行热更新以后，再杀掉app，再 进入，会再次检查热更新吗
```js
  const update = await codePush.checkForUpdate()
  const info = await codePush.getUpdateMetadata()

**Comment by kala888** [comment]
据我经验，代码里有个确认更新的过程，如果未确认之前杀了，下次重启会热更新。
