### ISSUE TITLE
大神，项目里的datav-app文件夹是什么？

### ISSUE THREAD

**Issue by wookkkkk** [kala888/nice-router-taro#40]
还有，这个框架支持Android和ios端吗？
看了已关闭的issue没有这个问题，期待您的解答
另外https://github.com/kala888/nice-router-taro/blob/master/tixwork-taro/docs/README.md里面的开发手册链接再次404了

**Comment by kala888** [comment]
datav-app是基于RN的项目，理论上支持android和ios，不过项目是做大屏的，支持ios没意义。

文档地址修复了，由于这个项目中有部分内容尚未开源（代码生成和后台），所有文档有些怪异有时候是错的。
