### ISSUE TITLE
运行项目报 Taro 配置有误的错误提示

### ISSUE THREAD

**Issue by Sean529** [kala888/nice-router-taro#5]
## 问题描述
我在 clone 项目并安装依赖后，执行 `yarn dev:weapp` 控制台报错。

![报错截图](https://qn.xiesz.com/AT/015158.png?blog)

## 期望
正常启动项目，大佬帮忙看看吧

**Comment by kala888** [comment]
看起来像是你本地权限问题，把整个工程目录chmod -R 755试试呢，还有现在nice router用的是taro3 beta6

**Comment by Sean529** [comment]
> 看起来像是你本地权限问题，把整个工程目录chmod -R 755试试呢，还有现在nice router用的是taro3 beta6

taro3后 mini 中没有 commonChunks 配置了。

![taro3文档 mini配置](https://qn.xiesz.com/AT/020337.png)

**Comment by kala888** [comment]
@XieShangZheng 确实，已经移除
