### ISSUE TITLE
没TS版本吗

### ISSUE THREAD

**Issue by OxYancy** [kala888/nice-router-taro#6]
没TS版本吗

**Comment by kala888** [comment]
> 没TS版本吗

准备后面改为ts的，随时关注

**Comment by fendou** [comment]
什么时候会有TS版？不知何年何月得偿所望？

**Comment by kala888** [comment]
master 已经改为TS了，V2是旧的版本@986244073

**Comment by kala888** [comment]
@fendou 基本完成改造，很多组件还需要精细化修改，敬请持续关注，有兴趣一起参与
