### ISSUE TITLE
请问 NavigationService.ajax 如何请求小程序的云函数？有 demo 吗？

### ISSUE THREAD

**Issue by anuxs** [kala888/nice-router-taro#8]
**看代码请求后台 url 是用NavigationService.ajax：** 
`componentDidMount() {

       NavigationService.ajax(Config.api.FooterHome, {}, {
         onSuccess: (resp) => {
           console.log(“”fetch data from backend,resp data:“”, resp)
           this.setState({
             pageTitle: resp.pageTitle,
           })
         },
       })
     }`

**api url 的定义：**
`
api: {

    FooterHome: "viewHomepage/,
    FooterMe: 'customerViewDashboard/',
    Login: 'clientLogin/',
    VerifyCode: 'sendVerifyCode/:mobile/',
    OSSToken: 'customGetOssToken/',
    Logout: 'logout/',
  },
`

**请问：我想要请求的后台是微信的云函数，该如何调用？：**
`
Taro.cloud.callFunction({

name: “add”,
  data: {
    x: 1,
    y: 2,
  }
}).then(res => {
  // output: res.result === 3
}).catch(err => {
  // handle error
})
`

**Comment by kala888** [comment]
没有使用云函数，但是可以你尝试把云函数调用封装到 backend.service.js中。
```
  const resp = await HttpRequest.send(options, loading) //改这
```

![image](https://user-images.githubusercontent.com/1215976/99493429-295be700-29aa-11eb-9bcd-fe29158d702b.png)
