### ISSUE TITLE
为什么每个模块都要重复引入react

### ISSUE THREAD

**Issue by superchangme** [kala888/nice-router-taro#9]
看了一下每一个文件里都写了
import React from 'react'
全局写一个不行吗

**Comment by kala888** [comment]
这个是React的特性，因为每个componet都是单独组件，编译后是类似React.createElement.......所以需要引入，但是可以通过webpack插件处理，你可以研究一下

**Comment by kala888** [comment]
@superchangme taro3.1.0开始升级到React17，现在版本，可以不用写了
```
import React from 'react'
```
